export const sampleData = [
  {
    id: 1,
    name: 'Ali Yılmaz',
    gender: 'Erkek',
    image: '/slide.jpg',
    passport: 'A123456789',
    citizwn: 'Türkiye',
    residence: 'Türkiye',
    birthDate: '1990-01-01',
    email: 'ali.yilmaz@medicabil.com',
    phone: '12345678901',
    workAdress: 'Nilüfer / Bursa : Mudanya Yolu Fethiye Mh. Küre Sk.No: 1 Nilüfer / Bursa',
    workTitle: 'omuz',
    arriveDate: '2023-10-01',
    departureDate: '2023-10-05',
    placeOfStay: 'Bursa',
    feverorChills: 'Evet',
    vomitedOrHadDiarrhoea: 'Evet',
    chronicDiseaseOrConditio: 'Evet',
    otherHealthProblems: 'Hayır',
    mainSurgicalInterests: 'Tümü',
    sozlesme: 'Evet',
    kvkk: 'Evet',
  },
]
