export const sliderData = [
  {
    id: 1,
    title: 'Meme Kanseri',
    description: 'Meme Kanseri hakkında bilgi',
    image: '/slide.jpg',
    status: 'Aktif',
    order: 1,
    date: '01.05.2025',
  },
  {
    id: 2,
    title: 'Uyku Laboratuvarı',
    description: 'Uyku Laboratuvarı hizmetleri',
    image: '/slide.jpg',
    status: 'Aktif',
    order: 2,
    date: '02.05.2025',
  },
  {
    id: 3,
    title: 'Saç Ekimi',
    description: 'Saç Ekimi işlemleri',
    image: '/slide.jpg',
    status: 'Devre dışı',
    order: 3,
    date: '03.05.2025',
  },
  {
    id: 4,
    title: 'Endoskopik Omurga Cerrahisi',
    description: 'Omurga cerrahisi detayları',
    image: '/slide.jpg',
    status: 'Aktif',
    order: 4,
    date: '04.05.2025',
  },
  {
    id: 5,
    title: 'Doktor',
    description: 'Doktorlarımız hakkında bilgi',
    image: '/slide.jpg',
    status: 'Devre dışı',
    order: 5,
    date: '05.05.2025',
  },
  {
    id: 6,
    title: 'Fizik Tedavi',
    description: 'Fizik tedavi hizmetleri',
    image: '/slide.jpg',
    status: 'Aktif',
    order: 6,
    date: '06.05.2025',
  },
  {
    id: 7,
    title: 'Check.Up',
    description: 'Check.Up paketleri',
    image: '/slide.jpg',
    status: 'Aktif',
    order: 7,
    date: '07.05.2025',
  },
  {
    id: 8,
    title: 'Ortopedi',
    description: 'Ortopedi tedavileri',
    image: '/slide.jpg',
    status: 'Devre dışı',
    order: 8,
    date: '08.05.2025',
  },
  {
    id: 9,
    title: 'Kardiyoloji',
    description: 'Kardiyoloji hizmetleri',
    image: '/slide.jpg',
    status: 'Aktif',
    order: 9,
    date: '09.05.2025',
  },
  {
    id: 10,
    title: 'Diyetisyen',
    description: 'Diyetisyen hizmetleri',
    image: '/slide.jpg',
    status: 'Aktif',
    order: 10,
    date: '10.05.2025',
  },
]
