export const sliderData = [
  {
    id: 1,
    title: 'Meme Kanseri',
    description: 'Meme Kanseri hakkında bilgi',
    image: '/slide.jpg',
    status: 'Aktif',
    order: 1,
    date: '2025-05-01 10:00:00',
  },
  {
    id: 2,
    title: 'Uyku Laboratuvarı',
    description: 'Uyku Laboratuvarı hizmetleri',
    image: '/slide.jpg',
    status: 'Aktif',
    order: 2,
    date: '2025-05-02 11:00:00',
  },
  {
    id: 3,
    title: 'Saç Ekimi',
    description: 'Saç Ekimi işlemleri',
    image: '/slide.jpg',
    status: 'Devre dışı',
    order: 3,
    date: '2025-05-03 12:00:00',
  },
  {
    id: 4,
    title: 'Endoskopik Omurga Cerrahisi',
    description: 'Omurga cerrahisi detayları',
    image: '/slide.jpg',
    status: 'Aktif',
    order: 4,
    date: '2025-05-04 13:00:00',
  },
  {
    id: 5,
    title: 'Doktor',
    description: 'Doktorlarımız hakkında bilgi',
    image: '/slide.jpg',
    status: 'Devre dışı',
    order: 5,
    date: '2025-05-05 14:00:00',
  },
]
