export const sliderData = [
  {
    id: 1,
    title: 'Meme Kanseri',
    description: 'Meme Kanseri hakkında bilgi',
    image: '/slide.jpg',
    status: 'Aktif',
    order: 1,
    date: '2025-05-01 10:00:00',
  },
  {
    id: 2,
    title: 'Uyku Laboratuvarı',
    description: 'Uyku Laboratuvarı hizmetleri',
    image: '/slide.jpg',
    status: 'Aktif',
    order: 2,
    date: '2025-05-02 11:00:00',
  },
  {
    id: 3,
    title: 'Saç Ekimi',
    description: 'Saç Ekimi işlemleri',
    image: '/slide.jpg',
    status: 'Devre dışı',
    order: 3,
    date: '2025-05-03 12:00:00',
  },
  {
    id: 4,
    title: 'Endoskopik Omurga Cerrahisi',
    description: 'Omurga cerrahisi detayları',
    image: '/slide.jpg',
    status: 'Aktif',
    order: 4,
    date: '2025-05-04 13:00:00',
  },
  {
    id: 5,
    title: 'Doktor',
    description: 'Doktorlarımız hakkında bilgi',
    image: '/slide.jpg',
    status: 'Devre dışı',
    order: 5,
    date: '2025-05-05 14:00:00',
  },
  {
    id: 6,
    title: 'Fizik Tedavi',
    description: 'Fizik tedavi hizmetleri',
    image: '/slide.jpg',
    status: 'Aktif',
    order: 6,
    date: '2025-05-06 15:00:00',
  },
  {
    id: 7,
    title: 'Check-Up',
    description: 'Check-Up paketleri',
    image: '/slide.jpg',
    status: 'Aktif',
    order: 7,
    date: '2025-05-07 16:00:00',
  },
  {
    id: 8,
    title: 'Ortopedi',
    description: 'Ortopedi tedavileri',
    image: '/slide.jpg',
    status: 'Devre dışı',
    order: 8,
    date: '2025-05-08 17:00:00',
  },
  {
    id: 9,
    title: 'Kardiyoloji',
    description: 'Kardiyoloji hizmetleri',
    image: '/slide.jpg',
    status: 'Aktif',
    order: 9,
    date: '2025-05-09 18:00:00',
  },
  {
    id: 10,
    title: 'Diyetisyen',
    description: 'Diyetisyen hizmetleri',
    image: '/slide.jpg',
    status: 'Aktif',
    order: 10,
    date: '2025-05-10 19:00:00',
  },
  {
    id: 11,
    title: 'Psikiyatri',
    description: 'Psikiyatri tedavileri',
    image: '/slide.jpg',
    status: 'Devre dışı',
    order: 11,
    date: '2025-05-11 20:00:00',
  },
  {
    id: 12,
    title: 'Göz Hastalıkları',
    description: 'Göz hastalıkları tedavileri',
    image: '/slide.jpg',
    status: 'Aktif',
    order: 12,
    date: '2025-05-12 21:00:00',
  },
  {
    id: 13,
    title: 'Dermatoloji',
    description: 'Cilt hastalıkları tedavileri',
    image: '/slide.jpg',
    status: 'Aktif',
    order: 13,
    date: '2025-05-13 22:00:00',
  },
  {
    id: 14,
    title: 'Nöroloji',
    description: 'Nöroloji hizmetleri',
    image: '/slide.jpg',
    status: 'Devre dışı',
    order: 14,
    date: '2025-05-14 23:00:00',
  },
  {
    id: 15,
    title: 'Kadın Doğum',
    description: 'Kadın doğum hizmetleri',
    image: '/slide.jpg',
    status: 'Aktif',
    order: 15,
    date: '2025-05-15 08:00:00',
  },
  {
    id: 16,
    title: 'Çocuk Sağlığı',
    description: 'Çocuk sağlığı hizmetleri',
    image: '/slide.jpg',
    status: 'Aktif',
    order: 16,
    date: '2025-05-16 09:00:00',
  },
  {
    id: 17,
    title: 'Acil Servis',
    description: 'Acil servis hizmetleri',
    image: '/slide.jpg',
    status: 'Devre dışı',
    order: 17,
    date: '2025-05-17 10:00:00',
  },
  {
    id: 18,
    title: 'Genel Cerrahi',
    description: 'Genel cerrahi hizmetleri',
    image: '/slide.jpg',
    status: 'Aktif',
    order: 18,
    date: '2025-05-18 11:00:00',
  },
  {
    id: 19,
    title: 'Kulak Burun Boğaz',
    description: 'KBB tedavileri',
    image: '/slide.jpg',
    status: 'Aktif',
    order: 19,
    date: '2025-05-19 12:00:00',
  },
  {
    id: 20,
    title: 'Estetik Cerrahi',
    description: 'Estetik cerrahi hizmetleri',
    image: '/slide.jpg',
    status: 'Devre dışı',
    order: 20,
    date: '2025-05-20 13:00:00',
  },
]
