const routes = [
  {
    path: '/',
    component: () => import('layouts/MainLayout.vue'),
    children: [
      { path: '', component: () => import('pages/dashboard/index.vue') },
      { path: 'header-menu', component: () => import('pages/header-menu/index.vue') },
      { path: 'footer-menu', component: () => import('pages/footer-menu/index.vue') },
      { path: 'homepage-settings', component: () => import('pages/homepage-settings/index.vue') },
      { path: 'gallery', component: () => import('pages/gallery/index.vue') },
      { path: 'pdf', component: () => import('pages/pdf/index.vue') },
      { path: 'popup', component: () => import('pages/popup/index.vue') },
      { path: 'prefix', component: () => import('pages/prefix/index.vue') },
      { path: 'hospital', component: () => import('pages/hospital/index.vue') },
      { path: 'magazine', component: () => import('pages/magazine/index.vue') },
      { path: 'video-tab', component: () => import('pages/video-tab/index.vue') },
      { path: 'home-service', component: () => import('pages/home-service/index.vue') },
      { path: 'cookie-text', component: () => import('pages/cookie-text/index.vue') },
      { path: 'address', component: () => import('pages/address/index.vue') },
      { path: 'slider', component: () => import('pages/slider/index.vue') },
      { path: 'faq', component: () => import('pages/faq/index.vue') },
      {
        path: 'center-of-excellence',
        component: () => import('pages/center-of-excellence/index.vue'),
      },
      { path: 'blog', component: () => import('pages/blog/index.vue') },
      { path: 'step-page', component: () => import('pages/step-page/index.vue') },
      { path: 'news', component: () => import('pages/news/index.vue') },
      { path: 'physician', component: () => import('pages/physician/index.vue') },
      { path: 'vlog', component: () => import('pages/vlog/index.vue') },
      { path: 'unit', component: () => import('pages/unit/index.vue') },
      { path: 'doctor', component: () => import('pages/doctor/index.vue') },
      { path: 'service', component: () => import('pages/service/index.vue') },
      { path: 'page', component: () => import('pages/page/index.vue') },
      { path: 'user', component: () => import('pages/user/index.vue') },
      { path: 'redirect', component: () => import('pages/redirect/index.vue') },
      { path: 'reference', component: () => import('pages/reference/index.vue') },
      { path: 'cooperation', component: () => import('pages/cooperation/index.vue') },
      { path: 'online-forms', component: () => import('pages/online-forms/index.vue') },
      {
        path: 'observer-physician-forms',
        component: () => import('pages/observer-physician-forms/index.vue'),
      },
      { path: 'settings', component: () => import('pages/settings/index.vue') },
    ],
  },
  {
    path: '/:catchAll(.*)*',
    component: () => import('pages/not-found/index.vue'),
  },
]

export default routes
