export const sampleData = {
  siteUrl: 'https://www.medicabil.com',
  appName: 'Medicabil',
  emailSenderName: 'Medicabil',
  emailSenderAddress: 'noreply@medicabildevde.com',
  adminEmail: 'santral@medicabil.com',
  reportErrors: '',
  twitter: 'https://twitter.com/Medicabil',
  facebook: 'https://www.facebook.com/Medicabil',
  googleAnalytics: 'UA-97870502-1',
  viber: '905323360868',
  foreignContactEmails: 'samet.bilgen@medicabil.com,medicabilhastanesi@gmail.com',
  thesisFormMail: 'aysun.yilmazlar@medicabil.com, ik@medicabil.com',
  foreignFormsMail: 'medicabilhastanesi@gmail.com,samet.bilgen@medicabil.com',
  visitorPhysicianFormMail: 'samet.bilgen@medicabil.com,medicabilhastanesi@gmail.com',
  siteVerification: '',
  supportEmail: 'info@medicabil.com',
  supervisorMail: 'info@medicabil.com,medicabilhastanesi@gmail.com,samet.bilgen@medicabil.com',
  youtube: 'https://www.youtube.com/user/medicabilhastanesi',
  instagram: 'https://www.instagram.com/medicabil/',
  githubSecret: '',
  googleTagManager: 'GTM-TG48TZD',
  whatsapp: '905323360868',
  onlineDrFormMail: 'medicabilhastanesi@gmail.com,samet.bilgen@medicabil.com',
  jobFormMail: 'medicabilhastanesi@gmail.com',
  contactFormMail: 'info@medicabil.com,medicabilhastanesi@gmail.com',
}
