export const sampleData = [
  {
    id: 1,
    title: 'Prof. Dr. Ali Yılmaz',
    description: 'Doktor hakkında bilgi',
    resume: '#### Prof. Dr. Ali Yılmaz',
    image: '/slide.jpg',
    doctorTitle: 'Prof. Dr.',
    name: 'Ali',
    surname: 'Yılmaz',
    specialization: null,
    appointmentLink: null,
    targetLink: 'https://dev.medicabil.com/tr/hekim/',
    service: 'Ortopedi',
    branch: 'Nilüfer Hastanesi',
    unit: 'Check Up',
    order: 1,
    isActive: true,
    hasAppointment: false,
    vitrine: false,
    date: '2025-05-01',
  },
  {
    id: 2,
    title: 'Prof. Dr. Ayşe Demir',
    description: 'Doktor hakkında bilgi',
    resume: '#### Prof. Dr. Ayşe Demir',
    image: '/slide.jpg',
    doctorTitle: 'Prof. Dr.',
    name: 'Ayşe',
    surname: 'Demir',
    specialization: null,
    appointmentLink: null,
    targetLink: 'https://dev.medicabil.com/tr/hekim/',
    service: 'Ortopedi',
    branch: 'Nilüfer Hastanesi',
    unit: 'Check Up',
    order: 2,
    isActive: true,
    hasAppointment: true,
    vitrine: true,
    date: '2025-05-02',
  },
  {
    id: 3,
    title: 'Prof. Dr. Mehmet Kaya',
    description: 'Doktor hakkında bilgi',
    resume: '#### Prof. Dr. Mehmet Kaya',
    image: '/slide.jpg',
    doctorTitle: 'Prof. Dr.',
    name: 'Mehmet',
    surname: 'Kaya',
    specialization: null,
    appointmentLink: null,
    targetLink: 'https://dev.medicabil.com/tr/hekim/',
    service: 'Ortopedi',
    branch: 'Nilüfer Hastanesi',
    unit: 'Check Up',
    order: 3,
    isActive: false,
    hasAppointment: false,
    vitrine: false,
    date: '2025-05-03',
  },
  {
    id: 4,
    title: 'Prof. Dr. Elif Şahin',
    description: 'Doktor hakkında bilgi',
    resume: '#### Prof. Dr. Elif Şahin',
    image: '/slide.jpg',
    doctorTitle: 'Prof. Dr.',
    name: 'Elif',
    surname: 'Şahin',
    specialization: null,
    appointmentLink: null,
    targetLink: 'https://dev.medicabil.com/tr/hekim/',
    service: 'Ortopedi',
    branch: 'Nilüfer Hastanesi',
    unit: 'Check Up',
    order: 4,
    isActive: true,
    hasAppointment: true,
    vitrine: false,
    date: '2025-05-04',
  },
  {
    id: 5,
    title: 'Prof. Dr. Ahmet Çelik',
    description: 'Doktor hakkında bilgi',
    resume: '#### Prof. Dr. Ahmet Çelik',
    image: '/slide.jpg',
    doctorTitle: 'Prof. Dr.',
    name: 'Ahmet',
    surname: 'Çelik',
    specialization: null,
    appointmentLink: null,
    targetLink: 'https://dev.medicabil.com/tr/hekim/',
    service: 'Ortopedi',
    branch: 'Nilüfer Hastanesi',
    unit: 'Check Up',
    order: 5,
    isActive: false,
    hasAppointment: false,
    vitrine: true,
    date: '2025-05-05',
  },
  {
    id: 6,
    title: 'Prof. Dr. Zeynep Yıldız',
    description: 'Doktor hakkında bilgi',
    resume: '#### Prof. Dr. Zeynep Yıldız',
    image: '/slide.jpg',
    doctorTitle: 'Prof. Dr.',
    name: 'Zeynep',
    surname: 'Yıldız',
    specialization: null,
    appointmentLink: null,
    targetLink: 'https://dev.medicabil.com/tr/hekim/',
    service: 'Ortopedi',
    branch: 'Nilüfer Hastanesi',
    unit: 'Check Up',
    order: 6,
    isActive: true,
    hasAppointment: false,
    vitrine: false,
    date: '2025-05-06',
  },
  {
    id: 7,
    title: 'Prof. Dr. Murat Aksoy',
    description: 'Doktor hakkında bilgi',
    resume: '#### Prof. Dr. Murat Aksoy',
    image: '/slide.jpg',
    doctorTitle: 'Prof. Dr.',
    name: 'Murat',
    surname: 'Aksoy',
    specialization: null,
    appointmentLink: null,
    targetLink: 'https://dev.medicabil.com/tr/hekim/',
    service: 'Ortopedi',
    branch: 'Nilüfer Hastanesi',
    unit: 'Check Up',
    order: 7,
    isActive: true,
    hasAppointment: true,
    vitrine: false,
    date: '2025-05-07',
  },
  {
    id: 8,
    title: 'Prof. Dr. Fatma Karaca',
    description: 'Doktor hakkında bilgi',
    resume: '#### Prof. Dr. Fatma Karaca',
    image: '/slide.jpg',
    doctorTitle: 'Prof. Dr.',
    name: 'Fatma',
    surname: 'Karaca',
    specialization: null,
    appointmentLink: null,
    targetLink: 'https://dev.medicabil.com/tr/hekim/',
    service: 'Ortopedi',
    branch: 'Nilüfer Hastanesi',
    unit: 'Check Up',
    order: 8,
    isActive: false,
    hasAppointment: false,
    vitrine: true,
    date: '2025-05-08',
  },
  {
    id: 9,
    title: 'Prof. Dr. Hasan Güneş',
    description: 'Doktor hakkında bilgi',
    resume: '#### Prof. Dr. Hasan Güneş',
    image: '/slide.jpg',
    doctorTitle: 'Prof. Dr.',
    name: 'Hasan',
    surname: 'Güneş',
    specialization: null,
    appointmentLink: null,
    targetLink: 'https://dev.medicabil.com/tr/hekim/',
    service: 'Ortopedi',
    branch: 'Nilüfer Hastanesi',
    unit: 'Check Up',
    order: 9,
    isActive: true,
    hasAppointment: false,
    vitrine: false,
    date: '2025-05-09',
  },
  {
    id: 10,
    title: 'Prof. Dr. Emine Polat',
    description: 'Doktor hakkında bilgi',
    resume: '#### Prof. Dr. Emine Polat',
    image: '/slide.jpg',
    doctorTitle: 'Prof. Dr.',
    name: 'Emine',
    surname: 'Polat',
    specialization: null,
    appointmentLink: null,
    targetLink: 'https://dev.medicabil.com/tr/hekim/',
    service: 'Ortopedi',
    branch: 'Nilüfer Hastanesi',
    unit: 'Check Up',
    order: 10,
    isActive: false,
    hasAppointment: true,
    vitrine: false,
    date: '2025-05-10',
  },
]
