export const sampleData = [
  {
    id: 1,
    name: 'Ayhan',
    email: 'ayhan@irshi.co',
    authority: 'writer',
    date: '2025-01-01',
  },
  {
    id: 2,
    name: 'riza',
    email: 'riza@inbox.com',
    authority: 'writer',
    date: '2025-01-01',
  },
  {
    id: 3,
    name: 'Aytaç Aliyeva',
    email: 'aytac@irshi.co',
    authority: 'writer',
    date: '2025-01-01',
  },
  {
    id: 4,
    name: 'Muhammed',
    email: 'Marketing1@medicabil.com',
    authority: 'writer',
    date: '2025-01-01',
  },
  {
    id: 5,
    name: 'Şahnoza',
    email: 'marketing3@medicabil.com',
    authority: 'writer',
    date: '2025-01-01',
  },
  {
    id: 6,
    name: 'Elif Gönül',
    email: 'elifgnl88@gmail.com',
    authority: 'writer',
    date: '2025-01-01',
  },
  {
    id: 7,
    name: 'Muhammed (Arapça)',
    email: 'fayadmuhammed1@gmail.com',
    authority: 'writer',
    date: '2025-01-01',
  },
  {
    id: 8,
    name: 'bihter sertepe',
    email: 'bihter.sertepe@medicabil.com',
    authority: 'writer',
    date: '2025-01-01',
  },
  {
    id: 9,
    name: 'Sibel Medicabil (Uluslararası)',
    email: 'sibel.kurshumliu@medicabil.com',
    authority: 'writer',
    date: '2025-01-01',
  },
  {
    id: 10,
    name: 'Medicabil Seo',
    email: 'seo@medicabil.com',
    authority: 'admin',
    date: '2025-01-01',
  },
]
